# cmdy configuration file
# Add your custom commands here - they'll be OS-aware!
# Supported OS keys: linux, mac, windows, or any custom OS name

menu_options:
  - display: "update, upgrade, remove packages"
    commands:
      linux: "sudo apt update && sudo apt upgrade && sudo apt auto-clean"
      mac: "brew update && brew upgrade"

  - display: "display network configuration"
    commands:
      linux: "ip addr show || ifconfig"
      mac: "ifconfig"

  - display: "show disk space usage"
    commands:
      linux: "df -h"
      mac: "df -h"

  - display: "list running processes"
    commands:
      linux: "ps aux"
      mac: "ps aux"

  - display: "display system information"
    commands:
      linux: "uname -a && lscpu"
      mac: "system_profiler SPHardwareDataType"

  - display: "clean temp files and caches"
    commands:
      linux: "./scripts/cleanup.sh"
      mac: "./scripts/cleanup.sh"

  - display: "system health report"
    commands:
      linux: "./scripts/health-check.sh"
      mac: "./scripts/health-check.sh"
