menu_options:
  - shortcut: "1"
    name: "System Health Check"
    description: "Check system resources and health status"
    commands:
      linux: "htop"
      mac: "top"
      joeos: "top"
  
  - shortcut: "2"
    name: "Network Info"
    description: "Display network configuration"
    commands:
      linux: "ip addr show"
      mac: "ifconfig"
  
  - shortcut: "3"
    name: "Disk Usage"
    description: "Show disk space usage"
    commands:
      linux: "df -h"
      mac: "df -h"
  
  - shortcut: "4"
    name: "Process List"
    description: "List running processes"
    commands:
      linux: "ps aux"
      mac: "ps aux"
  
  - shortcut: "5"
    name: "System Info"
    description: "Display system information"
    commands:
      linux: "uname -a && lscpu"
      mac: "system_profiler SPHardwareDataType"
  
  - shortcut: "q"
    name: "Quit"
    description: "Exit the menu"
    commands:
      linux: "exit"
      mac: "exit"
